X-mode
frc937/swerving-learning-box pull request #10
Opened 2024-01-20 17:52 UTC by MarissaKoglesby

Implement enterXMode and bound it to the x button.

2024-01-20 18:34 UTC, Berdenson commented
needs irl testing

2024-01-20 20:30 UTC, willitcode requested changes
Minor-ish changes. Probably won't fix our constant spinning issue, but still necessary.

2024-01-20 20:30 UTC, willitcode commented on src/main/java/frc/robot/commands/EnterXMode.java
> +    return false;
Return true here—otherwise the command will never end

2024-01-20 20:30 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  private final EnterXMode enterXMode = new EnterXMode(drive);
Move this to below the giant comment that says COMMANDS. Giant disorganized command/subsystem spam at the top of RobotContainer = bad, as we learned last year.

2024-01-22 21:47 UTC, Berdenson commented
Changes suggested by @willitcode implemented

2024-01-22 22:02 UTC, willitcode approved these changes
Looks good—let's merge!

2024-01-22 22:03 UTC, merged